apiVersion: apps/v1
kind: Deployment
metadata:
  name: duoc-app
  labels:
    app: duoc-app
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: duoc-app
  template:
    metadata:
      labels:
        app: duoc-app
    spec:
      containers:
        - name: duoc-app
          image: 246571967396.dkr.ecr.us-east-1.amazonaws.com/duoc-lab:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: duoc-app-config
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
