name: Validación del Código

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check-code:
    name: Fase CI: Validación
    runs-on: ubuntu-latest  # Línea 10: Define el servidor de ejecución
    steps:                  # Línea 11: Etiqueta obligatoria para agrupar acciones
      - name: ⬇️ Checkout del Código
        uses: actions/checkout@v4

      - name: ⚙️ Configurar Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: 📦 Instalar Dependencias (npm ci)
        run: npm ci

      - name: 🔒 Verificar Compliance
        run: npm audit

      - name: 🧪 Ejecutar Pruebas Automatizadas
        run: npm test