name: Pipeline Principal CI/CD

on:
  push:
    branches: [ develop ]

jobs:
  test:
    uses: ./.github/workflows/template_test.yml
    with:
      node_version: '20'

  build:
    needs: test
    uses: ./.github/workflows/template_build.yml
    with:
      node_version: '20'
      aws_region: ${{ vars.AWS_REGION }}
      ecr_repository: ${{ vars.ECR_REPOSITORY }}
    secrets: inherit

  deploy:
    needs: build
    uses: ./.github/workflows/template_deploy.yml
    with:
      strategy: 'rolling-update'
      aws_region: ${{ vars.AWS_REGION }}
      cluster_name: 'duoc-eks-cluster-cli'
      k8s_yaml_path: './kubernetes.yml'
    secrets: inherit
